### ISSUE TITLE
Need to check 'hotkey by popup' feature before the next release

### ISSUE THREAD

**Issue by Totktonada** [qstardict/qstardict#11]
As I see libqxt library [was replaced](https://github.com/qstardict/qstardict/commit/bc744ba608332390c668ce0255b2256aa978bf08) with the upstream’s implementation. I forget certain changes, but remember that I changed the library somehow before using it with QStardict.

I think I should check 'hotkey by popup' feature before the next release. I going to do so on the week. This issue filed to let maintainers know about potential problems and track it if ones will found.

**Comment by a-rodin** [comment]
Hi! I'm actually going to revert the latest commit that uses submodule because it breaks Github automatic packaging of releases, but libqxt should be updated because without update the build fails on macOS with Qt5.

**Comment by a-rodin** [comment]
I've reverted back `qxt` directory, but updated it content from the upstream using `update.sh` script.

It looks like the feature doesn't work now, and there is an error `QObject::connect: No such signal QxtGlobalShortcut::activated(QxtGlobalShortcut *)` at startup. But previous version of the library just failed at build time.

**Comment by Totktonada** [comment]
Hi! I’ll dig into libqxt problems (on the week) and will check can we fix its on our side (w/o touch libqxt sources).

**Comment by Totktonada** [comment]
All works fine for me with [this patch](https://gist.github.com/Totktonada/97805f41ee1676f6f1309f792552008e) applied. The first part is trivial change for the `activated()` signal’s signature, which seems to be changed. The second one is necessary for me (on Linux) to build QStardict. The problem described in `/usr/include/qt5/QtCore/qcoreevent.h` and I’ll just copy its description here:

```
        /*
          If you get a strange compiler error on the line with None,
          it's probably because you're also including X11 headers,
          which #define the symbol None. Put the X11 includes after
          the Qt includes to solve this problem.
        */
```

The changes I made for libqxt is in 0dafd66b4fe933d0f4c78d278729e5439a7fcc68 (at the bottom of the long diff). I described it as “Fix Qxt for unregister global shortcut at disable”. Now I try to disable/enable back/change a hotkey and all seems to work good. Maybe some problems were fixed in the upstream—I don’t know. Anyway, now these libqxt changes look as being unnecessary.

**Comment by a-rodin** [comment]
Cool!

Do you want to create a PR, or I can commit the changes on my own?

**Comment by Totktonada** [comment]
I’m okay if you just commit it :)

I think it should be separated into two commits as each part of the patch solved its own problem.

**Comment by a-rodin** [comment]
I've committed them.
Also, for your information, I've created a PR to libqxt: https://bitbucket.org/libqxt/libqxt/pull-requests/49

**Comment by Totktonada** [comment]
Thanks, Alexander!

PR is good way to inform others about the problem, but libqxt is [no longer maintained](https://bitbucket.org/libqxt/libqxt/wiki/Home) and there are few odds the PR will merged.

An one more thought come into my mind: maybe we should apply libqxt patch at the top of libqxt master in the `update.sh` script to prevent that changes being rewritten at the next run of the script.

Alternatively we can mark all lines changed in QStardict’s version of libqxt with `// QSTARDICT` or smth like. That leave us some manual merging after `update.sh` run, but rewritten changes would be explicitly visible.

I think the first approach is better: maintaining patches for libqxt as patch files applied by `update.sh`.

**Comment by a-rodin** [comment]
It's a good point about applying custom patches on the fly, I've added it.
